query user($uuid: UUID!) {
  ownerByUuid(uuid: $uuid) {
    name
    ownerEmails {
      nodes {
        email
      }
    }
    ownerVcs {
      nodes {
        serviceId
        username
      }
    }
    teams {
      nodes {
        name
        teamApps {
          nodes {
            app {
              name
            }
          }
        }
      }
    }
    apps {
      nodes {
        name
        teamApps {
          nodes {
            team {
              name
            }
          }
        }
      }
    }
    username
    services {
      nodes {
        uuid
        alias
        description
        topics
        name
        owner {
          username
        }
      }
    }
  }
}