export default {
  all_coins: '/api/all_coins',
  get_firstpage_history: '/api/get_firstpage_history',
  get_coin_history: '/api/get_coin_history',
  get_coin: '/api/get_coin',
  get_markets_by_coin: '/api/get_markets_by_coin',
  login: `/management/login`,
  coin: `/api/coin`,
  spider: `/api/spider/coin`,
  spiderList: `/api/spider/list`,
  crawler: `/api/crawler/detail`,
  updateCoin: `/api/crawler/updateCoin`,
  createStage: `/api/crawler/createStage`,
  createNews: `/api/crawler/createNews`,
  insertCoin: `/api/crawler/insertCoin`,
}
